version: '3'

services:
  app-docker-proxy:
    container_name: app-docker-proxy
    image: nginx
    volumes:
      - ./app/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/usr/share/nginx/html/index.html:/usr/share/nginx/html/index.html
    ports:
      - 8088:8080
  app-host:
    container_name: app-host
    image: nginx
    volumes:
      - ./app/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/usr/share/nginx/html/index.html:/usr/share/nginx/html/index.html
    network_mode: "host"
  proxy:
    container_name: proxy
    image: openresty/openresty
    volumes:
      - ./proxy/usr/local/openresty/nginx/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    network_mode: "host"
